### ISSUE TITLE
Broken Link for Configuration File

### ISSUE THREAD

**Issue by gerardsimons** [freqtrade/freqtrade-strategies#106]
In the readme.md there is a question about the configuration file that was used, called 

**Can I have your configuration file?**

But the link is broken. I think having the config file used to create the given results is important so it's worth fixing I think.

**Comment by xmatthias** [comment]
You're right, we'll remove this link.

The results displayed are there just to give an estimate - not to serve as a precise, 100% reproducible result.
Also, they were created in 2018, against data from 2018 - many things in freqtrade have been improved since - so the results may or may not be longer relevant.
Also, markets were quite different early 2018 than they are today - so results from 2018 will no longer be relevant.

Particular results per strategy will ALWAYS depend on the market used (BTC / USDT / EUR, ...) - on the pairs used, and also on the timerange / timeframe used - and are therefore something very specific to how you intend to use them.

I may not be successful with a particular strategy in ETH markets (for example) - but by using that same strategy against a different market (or different exchange) - the strategy can become profitable for you.


I'm still undecided if i should remove the results table as well due to the above reasons - but i guess i'll leave it for now as it can serve as "get a general idea"  approach.
I will however add a note that users's results may vary due to to the above reasons

**Comment by gerardsimons** [comment]
Excellent points raised, I think by providing that as explicit info in the readme would be sufficient. People are tempted to get the config and get started, but like you said it's hard to say whether that will hold for anyone.
