### ISSUE TITLE
Strategies not making any trades (while backtesting or "paper" live testing)

### ISSUE THREAD

**Issue by NPSconsultingLLC** [freqtrade/freqtrade-strategies#150]
Hi - 

First off thank you for the efforts on this project! I have Freqtrade installed on a Raspberry PI. 

Everything appears to be up and running properly, I have downloaded historical data for the past 100 days, and run the "freqtrade backtesting --strategy Strategy002" command, and when I do I get an output that shows a grid with 0 trades made. I have also tried turning the bot on in paper mode, and let it run for ~36 hours, and again saw 0 trades made. I am sure I have some setting incorrect but I'm not sure where to look to start debugging. Thanks for any assistance in advance.

**Comment by NPSconsultingLLC** [comment]
![image1](https://user-images.githubusercontent.com/6217367/113584358-6be82e00-95f0-11eb-90c2-1e5df934bb5a.png)
![image0](https://user-images.githubusercontent.com/6217367/113584363-6ee31e80-95f0-11eb-982a-b2b2407afda5.png)


Attaching images for additional info

**Comment by xmatthias** [comment]
It's text for a reason - please don't make screenshots of log output, but post the log output as text (wrapped in tripple ` so it's formatted proberly by github).
That will not just help me help you - but will also help others as then your log output becomes searchable.


Your configuration is simply wrong / misconfigured.
For binance, the minimum stake is 10(ish)$ - but i'd recommend to use something > 15$, otherwise you may still encounter problems as the amount can be too low.
As backtesting is checking for the minimum stake amount, all trades are rejected because you cannot buy ANY asset for 0.1$.

Increase your stake-amount to 20$ and you'll see trades.
Assuming you run the same config in paper trading, then the same will happen (although it's still also possible that the strategy simply found no buy possibility in multiple days - that's what backtsting would tell you).

**Comment by NPSconsultingLLC** [comment]
Thank you for the super quick response. And yes that was absolutely the issue. I'm still learning a lot here. 

I'm happy to repost the data as text if you think it would be valuable.

**Comment by xmatthias** [comment]
> I'm happy to repost the data as text if you think it would be valuable.

it's ok ... but for next time ... ;)
