### ISSUE TITLE
Questions about AI

### ISSUE THREAD

**Issue by nodwan** [freqtrade/freqtrade-strategies#159]
hi, i‘was look your free content. first thanks to make it public! i‘know it is always a hard work. so but here is a smal question, about ML . it is possible to optimize a running strategy by hereself with ML and i ask myself always why, nobody use tensorflow to optimize buy and sell signals in realtime. AI Trading, in my opinion will be the future. about this i’think why nobody bring AI to freqtrade in realtime ... maybe you have an answer ... 

thanks ...

**Comment by xmatthias** [comment]
Just because you're not seeing it here does not mean nobody did it so far.
this can mean anything between 

* nobody tried to do it (unlikely)
* somebody tried to do it and failed
* somebody succeeded, is rich now, but doesn't want to share

Freqtrade itself would support a tensorflow-based strategy just fine (it'll not care what other libraries you use) as long as the strategy interface is adhered by.
If you're keen on looking into it, feel free to try and contribute it to this repository ... 


you will however notice that to properly train a model, you'll need labeled data - and labeling data to properly work is not easy.
it's also quite easy to have "future-looking" algorithms - which use data that should not be available at that point in time - which will look great in tests, and fail miserably in live trading.

You'll also suffer to understand trading decisions, which will make you more likely to switch it off after a few days of "bad runs" ...

**Comment by mablue** [comment]
See GodStra and GodStraHo.maybe it will helpfull for making new god strategys based on tensorflow

**Comment by nodwan** [comment]
thanks, for answer unfortunate, i‘m not a programmer, but a good analyst, something work or not. i‘was years use gecko as my favorit bot. this year now i‘start with ft and i’love it. and godstra, yes i‘love this strat too. ai will the futher of trading an my hope is one day ft will run with tensorflow in the background.

**Comment by mablue** [comment]
> thanks, for answer unfortunate, i‘m not a programmer, but a good analyst, something work or not. i‘was years use gecko as my favorit bot. this year now i‘start with ft and i’love it. and godstra, yes i‘love this strat too. ai will the futher of trading an my hope is one day ft will run with tensorflow in the background by train itself with training periode, before it‘s start real trading.
> i‘remember a NN strategy with gecko, there was a warm up Periode before the strategy was start make real trades … may this is also a way to let learn tenserflow by him self. i‘m not a programmer, so may i‘dont know something like that is possible.

Was nn stra of gekko profitable ir not?in real?

**Comment by nodwan** [comment]
yes, it was, not so but only little … freqtrade make more

**Comment by mablue** [comment]
> yes, it was, not so but only little … freqtrade make more
Ow tnx for help
I think GodStra on freqtrade some times make fucking much more profit instate of other strategies!
We just need an hpc to generate a real GOD strategy.
Which strategy you use for it?can you share with me your strategys?

**Comment by StanWijn** [comment]
@mablue We are also searching for NN strategies that were previously implemented in Gekko Trader. See these examples: https://deandree.medium.com/can-neural-networks-beat-the-crypto-market-of-september-part-4-66547b5fe415

However, the currenty DevilStra looks even more advanced compared to some of these NN strategies, so I doubt if these really improve the outcome much. Thanks mablue!

**Comment by mablue** [comment]
> @mablue We are also searching for NN strategies that were previously implemented in Gekko Trader. See these examples: https://deandree.medium.com/can-neural-networks-beat-the-crypto-market-of-september-part-4-66547b5fe415
> 
> However, the currenty DevilStra looks even more advanced compared to some of these NN strategies, so I doubt if these really improve the outcome much. Thanks mablue!

I working on a new method now.
jumky strategy is up.
see that repo:
http://github.com/mablue/mastrade

**Comment by roko772** [comment]
I wrote something like NN strategies. V2 is meant to be single layer strategy, V3 - as triple layer one.
It may be written in worst possible way, but I'm a noob, so please, don't throw tomatoes to me :)
[https://github.com/roko772/RokoNeural](url)

**Comment by xmatthias** [comment]
With the addition of freqAI to freqtrade - i think this question is now obsolete.
