### ISSUE TITLE
 How to unstand `HourBasedStrategy.py`

### ISSUE THREAD

**Issue by BourneSuper** [freqtrade/freqtrade-strategies#244]
*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*

## Step 1: What indicators are required?

`dataframe['hour'] = dataframe['date'].dt.hour`

## Step 2: Explain the Buy Strategy
Buying pairs depends on clock time. For example, at  6:00  would buy it.
`(dataframe['hour'].between(min, max))`

## Step 1: Explain the Sell Strategy

Selling pairs depends on clock time. For example, at  6:00 would buy it.
`(dataframe['hour'].between(min, max))`

## Source

What come from this strategy? Cite your source:
[HourBasedStrategy.py](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/HourBasedStrategy.py)

## Topic
I tried `HourBasedStrategy.py` in this repository. And this strategy can reach a very high profit ( 200% or more ) just depending on time.
 How to unstand this reulst? Are other indicators useless ? Is this market a joke?

**Comment by xmatthias** [comment]
> Is this market a joke?

all markets (including crypto markets) follow certain patterns.
In crypto, these patterns are slightly different than in traditional markets (because crypto trades 24/7).
Depending on the markets - it's very well possible that depending on time, pairs move in certain patterns. 


In my suspicion (also talking to others) - this often follows traditional market times of different markets (EU / APO / AME) - as it'll usually be institutional money that "really" moves big markets (like BTC) - which is most likely operated by clerks working 9/5 ... 

It's simply one type of trading - the strategy itself is really made to show how to do something like this (you'd probably want to combine this with other indicators to not trade against the trend) - but as with all other strategies provided here - it'll have profitable periods, it'll have down periods - but real resuts will depend on the parameters picked by the user (exchange, markets, ...).
