### ISSUE TITLE
finta problem

### ISSUE THREAD

**Issue by mahmutpolattt** [freqtrade/freqtrade-strategies#306]
Hello. I'm getting a finta error when running a strategy in Freqtrade. I couldn't solve it. Can you help me?

![problem](https://github.com/freqtrade/freqtrade-strategies/assets/157739036/a247e982-b5ef-4f5b-a292-9c0c884df53d)

**Comment by xmatthias** [comment]
Seems like you're missing a dependency required by that strategy (in this case, finta).

Freqtrade installs the  libraries listed in [the docs](https://www.freqtrade.io/en/stable/strategy-customization/#indicator-libraries) by default.
If your strategy uses different libraries, it's the user's responsibility to install them before use.

**Comment by froggleston** [comment]
@mahmutpolattt be aware that the Machete strategy has lookahead bias (the chikou span indicator looks into the future in backtesting), so the backtests look amazing and dry/live results will be poor. I presume you picked up that strategy due to a YouTube video, so please only use it for learning purposes.
