### ISSUE TITLE
AverageHyperOpt Script

### ISSUE THREAD

**Issue by liamodev** [freqtrade/freqtrade-strategies#77]
## Source
 https://github.com/freqtrade/freqtrade-strategies/commit/ab9cba8d74e990ea6db7008f3fe530d081ac5989

Thanks, here are two videos from the run, both stopped at 28 evaluations.

https://www.screencast.com/t/21negUipXOD -12 min long (stops flashing at 1:35 and no change for the rest of the video, you can see the cores reduce to 1/4)

https://www.screencast.com/t/vffx86lApCAa - 6 min long (same as above)

Not I did run this for about an hour and it got a bit past 30, maybe 35 evaluations or similar.

**Comment by hroff-1902** [comment]
which is MACrossOpt?

**Comment by liamodev** [comment]
Sorry, I should have clarified that, its a copy of the code from AverageHyperOpt with a more descriptive name.
[MACross.zip](https://github.com/freqtrade/freqtrade-strategies/files/4503051/MACross.zip)
.

**Comment by allobet** [comment]
Hi, the same thing happens to me with a "custom" code but based on AverageHyperopt, it goes smoothly until 28th epoch is reached, then gets stuck, and now 1 hour later, stills there.

**Comment by allobet** [comment]
After 2 hours or so it moves to epoch 32 and then get "stuck" another time so I suppose it's a matter of time... maybe it's an obvious thing but i can't understand why some epochs are so fast and others are so so slow. Also I noticed if I run for less than 30 epochs runs ok but if it's greater always stuck at 28th

**Comment by hroff-1902** [comment]
>  but i can't understand why some epochs are so fast and others are so so slow

The time needed for hyperopting an epoch depends on the number of trades in it, I guess even worse than lenear, seems to be a square dependency. Maybe (seems to be) suboptimal. I tried to find a reason many times in the last year...

**Comment by hroff-1902** [comment]
it's "stuck" after 30th actually -- first 30 epochs are generated randomly in the hyperspace, then scikit-optimize starts fitting the models.

@allobet can you watch the memory consumption -- maybe you are getting swapping after first 30 random points

**Comment by xmatthias** [comment]
Well what's your system? 
how much memory does the system have / how many cores?

@hroff-1902 can it be a problem of random number initialization or would that happen earlier?
not enough random values available in the system -> generating one random value takes a long time?

I've had this once a long time ago (not with python though - with linux level stuff - don't remember what exactly) ... but i had to run a "random initialization" after startup to get that fixed...

**Comment by hroff-1902** [comment]
> @hroff-1902 can it be a problem of random number initialization or would that happen earlier?
> not enough random values available in the system -> generating one random value takes a long time?

I neither heard of such behavior before nor can reproduce it

**Comment by liamodev** [comment]
> cannot reproduce
> 
> try to run with `-j 1` option

Same issue.

**Comment by hroff-1902** [comment]
can you add some prints in your hyperopt methods to see if it's one of the statements calculating conditions, which takes long time?

**Comment by liamodev** [comment]
> Well what's your system?
> how much memory does the system have / how many cores?

Tried with different servers 4-64gb ram and 2-32 cores, same result.

I think you have identified it, that the first 30 are random then it's working hard to find direction within its learning trees, with MA crosses the changes are inter dynamic meaning they actually affect each other little correlation.

If you have search ranges of 30 per MA (MA1 crossing MA2 for entry and MA3 crossing MA4 for exit), that becomes a big search window (almost a million combinations).

I'll try with a simpler MA strategy.

**Comment by ozitrance** [comment]
I am experiencing the exact same behavior. Up to 29 epochs all good - takes seconds to complete. 30 and over it takes way way longer... During the time it hangs, it looks like only 1-2 threads are actually doing anything (always CPU4 & CPU17 in my case, not sure if it means anything).

I'm using an 18 cores/36 threads cpu, 256gb ram. 

Limiting the the job workers doesn't seem to matter - if I limit it to 10 I can see the first 20 epochs results right away and then it hangs.

Increasing the random-state doesn't seem to make any difference either. Even with `--random-state 50` I get the same behavior. Also if I use `--random-state 10` with `-e 29` it still works fine and done in seconds.

Only thing that seems to make any difference is limiting the EMA ranges at the top of the file - if I use a small range it works much faster - bigger one and it starts to be slower after epoch 30... 

Anyone figured this out? Any ideas why 30? I can provide more information if needed.

BTW Thank you for this amazing tool and unbelievable work you all put into it. No words can describe how much how love you all :)  thank you :1st_place_medal:

**Comment by xmatthias** [comment]
@ozitrance 
The "slowdown" after 30 epochs is natural, and i don't think there's anything to do against this, as it's simply the nature of baesian search.
For a baesian search, you need a number of initial points. In hyperopt, we use 30 - therefore the first 30 results are totally random points, without any logic in improving results.

After this, baesian search kicks in - which analyzes ALL previous points and finds the next best point based on previous results.
Obviously, reducing the search space will improve this "delay" - as it's less effort to find the next best line in a 3D space than it is in a 64 Dimensional space.

Unfortunately, the baesian algorithm is NOT parallelizable (or not well, didn't look that much into details), so hyperopt will run the backtests in parallel - and then do the baesian search on one core (that's why cpu usage drops to 1 core at regular intervals).

There's also an issue in the scikit-optimize repository, which contains a link which describes the mathematical details / limitations of this:  https://github.com/scikit-optimize/scikit-optimize/issues/968

There is therefore nothing we can do against the "slowdown" noticed. Feel free to open an issue in the scikit-optimize repository for this to discuss how to improve this (or try to fix it there) - but i don't think it'll be possible due to the mathematical limitations.

**Comment by ozitrance** [comment]
Thank you @xmatthias for the detailed answer. I understand the idea here and of course it makes sense. I’m just wondering why 30? Is that number still stays relevant even if I change the `—random-state` parameter? I tried both more and less than 30 and that didn’t seem to matter. Is it hard coded somewhere else?

**Comment by xmatthias** [comment]
random-state is just the random seed used to get the random points.

It's just a "random" number you - but by using the same number twice, you'll get the same results.
If you don't pass it in, a random "random-state" will be generated and plotted.

It got NOTHING to do with this whatsoever, the only point of `--random-state` is to give you reproducible results (assuming you don't change anything else, obviously).

---

the 30 comes from experimentation - but is a arbitrary number in reality.

Think about how baesian search works (best as 3d structure, or as a 3d map with peaks and valleys).

It's a 3d Plane with multiple local minima (holes / valleys), and you pick 30 random points in this plane. Each of these points serves as starting point for further investigation - and your goal is to find the lowest valley.
some points may already be in a valley, while others are right on a peak (looking into multiple valleys).

If you pick to few of these points, you'll likely be stuck in the next-best valley forever, without even knowing there's other, lower (better) valleys.

Obviously if you pick too many, calculations will take longer as you got more starting points, but the chance of getting the "best" valley increases. 30 has shown to be a good tradeoff between the 2.

Due to how this works, we recommend to not run more than maybe ~1000 Epochs at once, and then "rerun" the same hyperopt file, which will get different results (obviously without --random-state - so it's different  random starting points each time).

This is due to one of the problems with baesian search - once if is in a valley, it sometimes keeps there without finding a way out to a better (completely different) valley.

**Comment by ozitrance** [comment]
Thank you @xmatthias for this explanation. I was reading it wrong from the documentation and now it’s all clear. I was also able to find it in the code and just quickly change it to test it. It’s definitely that

thank you
 🙏
